apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatekeeper-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatekeeper-ui
  template:
    metadata:
      labels:
        app: gatekeeper-ui
    spec:
      containers:
        - name: gatekeeper-ui
          image: pratapgowda/gatekeeper-ui:v0.02
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
          - containerPort: 8080
            name: web
          env:
          - name: ASPNETCORE_URLS
            value: "http://+:8080"
      serviceAccountName: gatekeeper-ui