---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: gatekeeper-ui
rules:
  - apiGroups: 
      - "constraints.gatekeeper.sh"
      - "templates.gatekeeper.sh"
    resources:
      - "*"
    verbs:
      - "get"
      - "list"
---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: gatekeeper-ui
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gatekeeper-ui
subjects:
  - name: gatekeeper-ui
    namespace: gatekeeper-system
    kind: ServiceAccount